services:
  postgres:
    image: postgres:14
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openguild
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./base_schema.sql:/docker-entrypoint-initdb.d/base_schema.sql:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: local_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@openguild.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
